### ISSUE TITLE
Visa antal enheter i godsdeklaration

### ISSUE THREAD

**Issue by wsv-chas** [wsv-accidis/fm-fg-godsdekl#1]
När ett ämne med NEM lastas anges antal enheter (t ex antal patroner) vid lastningen men i själva godsdeklarationen visas bara NEM för hela lasten. Uppgiften om antal enheter krävs inte enligt SäkI Tp FG men kan vara bra att ha för användaren.

Lägg till en option att visa antal enheter i godsdeklarationen (likn. optionen att visa M-nr).

**Comment by wsv-accidis** [comment]
Visas alltid; bra att ha och gör ingen skada.
