### ISSUE TITLE
Lägg till batterier och SIGNRÖKHGR 11

### ISSUE THREAD

**Issue by wsv-chas** [wsv-accidis/fm-fg-godsdekl#9]
Lägg till följande mtrl i appen:

- Batterier, litiumbatterier och svavelsyra, UN 2794, 2795, 2796, 3090, 3091, 3480 och 3481
- SIGNRÖKHGR 11 (fyra färger, på sid 139 i AmKat), förmodligen UN 0303 men behöver bekräftas.

**Comment by wsv-accidis** [comment]
M4742-100601 SIGNRÖKHGR 11 RÖD
M4742-100611 SIGNRÖKHGR 11 GRÖN
M4742-100621 SIGNRÖKHGR 11 BLÅ
M4742-100631 SIGNRÖKHGR 11 ORANG

- UN 0303 RÖKAMMUNITION (måste bekräftas)
- Etikett 1.4G (måste bekräftas)
- NEM 0,193 kg
- Tpkat 2 (om UN 0303)
- Tunnelkod E (om UN 0303)
